# Generated by Django 4.0.3 on 2022-07-01 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emission_calculator', '0003_carbonscore_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.OneToOneField(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='emission_calculator.carbonscore'),
        ),
    ]
