# Generated by Django 4.0.3 on 2022-07-01 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emission_calculator', '0006_remove_carbonscore_parents_carbonscore_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emission_calculator.carbonscore'),
        ),
    ]
